repository_type: pipeline
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/multiqc_config.yml
    - assets/nf-core-nfstem_logo_light.png
    - conf/base.config
    - pyproject.toml
    - docs/images/nf-core-nfstem_logo_light.png
    - docs/images/nf-core-nfstem_logo_dark.png
    - .github/.dockstore.yml
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - assets/email_template.html
    - assets/email_template.txt
    - assets/sendmail_template.txt
    - conf/modules.config
    - docs/output.md
    - docs/README.md
    - docs/usage.md
    - conf/igenomes.config
    - conf/igenomes.config
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nfstem_logo_light.png
    - docs/images/nf-core-nfstem_logo_light.png
    - docs/images/nf-core-nfstem_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - process.cpus
    - process.memory
    - process.time
    - custom_config
  multiqc_config:
    - report_comment
  readme:
    - nextflow_badge
